apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rc-game
spec: 
  replicas: 4
  selector: 
   matchLabels:
    env: dev
  template:
   metadata:
     name: tmp-game
     labels:
       env: dev
   spec:
      containers:
      - name: c1
        image: abhinagare/abhi-new-repo:v2
        ports:
        - containerPort: 80
