apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-game
spec:
  replicas: 3
  selector:
   env: dev
  template:
   metadata:
     name: tmp-game
     labels:
       env: dev
   spec:
     containers:
      - name: c1
        image: abhinagare/abhi-new-repo:v2
        ports:
        - containerPort: 80
      
